In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\rebelkit\data.csv')

In [3]:
df.head()

        fever  bodyPain  age  runny Nose  diff Breath  Infection Prob
0   98.905309         1   59           0            0               1
1  101.595306         1   99           0            0               1
2   99.695996         1   76           1            0               0
3  100.708725         0   25           0            0               0
4   98.663576         1   90           1           -1               0

In [4]:
df.tail()

           fever  bodyPain  age  runny Nose  diff Breath  Infection Prob
2946  100.144509         1   69           0            1               0
2947  100.866879         1   65           1            1               0
2948   99.168006         0   73           1            0               1
2949  100.449550         1   66           0           -1               1
2950   99.962778         0   76           1           -1               1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2951 entries, 0 to 2950
Data columns (total 6 columns):
fever             2951 non-null float64
bodyPain          2951 non-null int64
age               2951 non-null int64
runny Nose        2951 non-null int64
diff Breath       2951 non-null int64
Infection Prob    2951 non-null int64
dtypes: float64(1), int64(5)
memory usage: 138.4 KB

In [6]:
df['diff Breath'].value_counts()

-1    1009
 0     993
 1     949
Name: diff Breath, dtype: int64

In [7]:
import numpy as np

In [8]:
def data_split(data, ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * ratio)
    test_indices = shuffled [:test_set_size]
    train_indices = shuffled [test_set_size:]
    return data.iloc[train_indices], data.loc[test_indices]

In [9]:
np.random.permutation(7)

array([4, 6, 0, 5, 2, 3, 1])

In [10]:
train, test = data_split(df, 0.2)

In [11]:
train

           fever  bodyPain  age  runny Nose  diff Breath  Infection Prob
2333   98.001113         0   13           1           -1               0
1978   98.776186         1   42           0            0               0
259    99.497554         0   34           1            0               1
1200  101.160197         1   58           0           -1               1
2350  100.539535         1   72           1            0               1
2594   98.156137         0   23           1            0               0
1330   99.314196         1   55           1            1               0
2365  101.301457         0   33           0           -1               0
2894  100.421325         1   92           0            1               0
2712  100.159325         0    8           1            0               0
1494   98.883347         0   27           1            0               1
2669   99.480623         1   33           0            1               0
2282   99.224758         0  100           0            1               1
456    99.132018         0   35           0           -1               1
462   100.929558         1   37           1           -1               0
2181  101.548042         1   94           0           -1               1
642    98.750051         1   78           1           -1               1
381   101.348956         1    4           1           -1               1
2398  100.661040         0   41           0            1               0
612    99.578598         1   77           1            1               1
2881  100.580824         1   89           1            0               1
2007   99.129801         1   70           1            1               1
2247  101.424734         1   68           1            1               1
2916  100.936870         1   42           1           -1               0
1614   98.108989         1   81           1            1               1
787    98.884247         1   90           1            1               0
1105   99.296535         1   76           1            0               1
2873   98.655974         0   73           0            0               1
2244  100.571414         0   87           1            0               1
1945   98.293874         0   54           1            0               1
...          ...       ...  ...         ...          ...             ...
1082  101.374564         1   89           1            1               0
474   101.085035         1   17           1           -1               0
2904   98.313824         1    4           0            1               1
747    99.956130         0   59           1            1               1
2300  100.020831         1   80           1            0               1
21    101.772427         1   34           0           -1               1
459    99.672586         0   59           0           -1               1
1184  101.338663         1   37           1           -1               1
2324   98.906165         1   36           0           -1               0
955   100.383244         0   62           0           -1               0
1215  101.913959         1   74           0            1               1
2433  101.162868         0   39           1           -1               0
2853   99.194246         0    6           0            0               0
1515  101.888230         0   61           0            0               0
2391   99.667828         0    7           1            1               0
769    99.019639         0   39           1            0               1
1685  100.761653         0   10           0           -1               1
130   101.942067         1   15           1            1               0
2919   98.097208         0   67           0            0               1
2135   99.540471         1   63           1            1               1
1482   99.652670         1   60           1           -1               1
330   101.912925         1   42           1           -1               0
1238   99.423106         0   32           1           -1               1
466   101.287892         0   61           1            1               0
2169  100.396254         1   68           0           -1               0
1638  101.740269         1   56           1            1               0
1095   99.676515         0   70           0            0               0
1130   98.024151         0   94           1            0               1
1294   98.458700         0   65           1            0               0
860   100.982568         1   53           1           -1               0

[2361 rows x 6 columns]

In [12]:
test

           fever  bodyPain  age  runny Nose  diff Breath  Infection Prob
790    99.020218         0   45           0            1               0
246    99.288067         0   53           0            0               1
2721   98.015432         1   20           1            1               1
2487  100.805211         0   12           1            0               0
2837  101.542561         0   57           1            1               0
2766   99.209372         0   91           1            0               1
1053  100.150362         0   41           1            1               1
1210   99.068771         1    1           0            1               0
2497  100.277280         0   62           1            1               0
1429  101.051029         1   45           1           -1               1
679    99.958627         1   79           0            0               1
1674   99.164719         0   92           1            0               0
944   101.132163         1   36           0           -1               0
1462   99.155599         0   74           1            0               1
2937   99.547802         1   36           1           -1               0
676   101.020794         0   45           1            0               1
929   101.205460         1   63           0            0               1
1206  100.437325         0   98           0            1               1
203   100.781094         1   64           0            0               0
1321   98.367901         0   62           1            1               1
602   101.261764         0   15           0            0               0
605    98.748486         0   97           1            0               0
1047   98.192671         1   71           0            0               0
1397   98.731385         0   30           1            1               0
1703   99.858829         0   13           0            1               1
2310  100.725958         0   35           0            1               0
1037   98.086202         0   19           0            1               1
2684   98.096759         1   83           1           -1               0
521   100.361993         1   83           0            1               0
175    98.541768         0   61           1           -1               1
...          ...       ...  ...         ...          ...             ...
1412   98.626516         0   32           0            0               1
564    98.504196         1   19           0            1               1
1517   98.727180         1   54           0           -1               1
809    98.265813         1   70           0           -1               0
212   101.426029         0   42           0           -1               1
12     98.196470         0   21           0            0               1
1543  101.064957         0   90           0            1               1
422   101.140866         1   35           1            0               1
2410   98.531745         1   56           1           -1               1
2593  100.016214         0   51           0            0               1
1161   99.442982         0   45           0           -1               1
1225  101.098081         0   89           0            1               1
1846  100.791197         1   98           0            1               1
509    99.028626         0   92           0           -1               0
2423   99.074528         0    8           0            0               0
2376   98.924982         0   45           0            1               0
1421  100.100968         0   13           0           -1               1
2597   98.761318         1    9           0           -1               0
518   100.440840         1   16           1            0               1
2742  101.013938         1   64           1           -1               1
573   100.234609         0   78           0           -1               0
1048  101.003408         0   90           0            0               0
1933   98.833682         1   79           1           -1               0
1847   99.928678         0   98           1           -1               0
1360  101.706595         1   50           1            0               0
2521   98.648813         1   53           0            1               1
1962   98.070828         0   35           1            0               1
1411   98.537676         1    7           1            0               0
2859  101.564117         0    7           1           -1               1
358    99.500518         1   12           0            0               0

[590 rows x 6 columns]

In [13]:
X_train = train[['fever', 'bodyPain', 'age', 'runny Nose', 'diff Breath']].to_numpy()
X_train

array([[ 98.00111342,   0.        ,  13.        ,   1.        ,
         -1.        ],
       [ 98.7761859 ,   1.        ,  42.        ,   0.        ,
          0.        ],
       [ 99.49755351,   0.        ,  34.        ,   1.        ,
          0.        ],
       ...,
       [ 98.02415111,   0.        ,  94.        ,   1.        ,
          0.        ],
       [ 98.45870024,   0.        ,  65.        ,   1.        ,
          0.        ],
       [100.9825679 ,   1.        ,  53.        ,   1.        ,
         -1.        ]])

In [14]:
X_test = test[['fever', 'bodyPain', 'age', 'runny Nose', 'diff Breath']].to_numpy()
X_test

array([[ 99.02021791,   0.        ,  45.        ,   0.        ,
          1.        ],
       [ 99.28806686,   0.        ,  53.        ,   0.        ,
          0.        ],
       [ 98.01543201,   1.        ,  20.        ,   1.        ,
          1.        ],
       ...,
       [ 98.53767567,   1.        ,   7.        ,   1.        ,
          0.        ],
       [101.5641169 ,   0.        ,   7.        ,   1.        ,
         -1.        ],
       [ 99.50051798,   1.        ,  12.        ,   0.        ,
          0.        ]])

In [15]:
 X_train = train[['fever', 'bodyPain', 'age', 'runny Nose', 'diff Breath']].to_numpy()

In [16]:
X_train

array([[ 98.00111342,   0.        ,  13.        ,   1.        ,
         -1.        ],
       [ 98.7761859 ,   1.        ,  42.        ,   0.        ,
          0.        ],
       [ 99.49755351,   0.        ,  34.        ,   1.        ,
          0.        ],
       ...,
       [ 98.02415111,   0.        ,  94.        ,   1.        ,
          0.        ],
       [ 98.45870024,   0.        ,  65.        ,   1.        ,
          0.        ],
       [100.9825679 ,   1.        ,  53.        ,   1.        ,
         -1.        ]])

In [17]:
Y_test = test[['Infection Prob']].to_numpy().reshape(590, )
Y_test

array([0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0], dtype=int64)

In [18]:
Y_train = train[['Infection Prob']].to_numpy().reshape(2361, )
Y_train

array([0, 0, 1, ..., 1, 0, 0], dtype=int64)

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
clf = LogisticRegression()
clf.fit(X_train, Y_train)

C:\Users\rebelkit\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [21]:
infprob = clf.predict_proba([[102, 1, 22, 1, 1]])[0][1]

In [22]:
infprob

0.5101885138272928